using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Stores the complete parts manifest for one engine.
/// Maps each part's GameObject name → PartData asset.
/// Generated by EnginePartSetupTool and referenced in EngineData.
/// At runtime, EngineSceneLoader applies this to every EnginePart on the spawned prefab.
/// </summary>
[CreateAssetMenu(fileName = "NewEnginePartManifest", menuName = "Engine VR/Engine Part Manifest")]
public class EnginePartManifest : ScriptableObject
{
    [Serializable]
    public class PartEntry
    {
        [Tooltip("Must match the GameObject name exactly.")]
        public string gameObjectName;
        public PartData partData;
    }

    public List<PartEntry> parts = new();

    /// <summary>Returns PartData for a given GameObject name, or null if not found.</summary>
    public PartData GetPartData(string goName)
    {
        foreach (var entry in parts)
            if (entry.gameObjectName == goName) return entry.partData;
        return null;
    }
}
